version: "3"

services:
  wiki:
    build: .
    container_name: wiki
    restart: always
    ports:
      - 7000:80
    volumes:
      # Uncomment below after initial setup
      # - ./LocalSettings.php:/var/www/html/LocalSettings.php
      - ./logo.png:/var/www/html/resources/assets/logo.png
      - ./favicon.ico:/var/www/html/favicon.ico
      - images:/var/www/html/images
      - ./backups:/backups

volumes:
  images: